### ISSUE TITLE
confusing description

### ISSUE THREAD

**Issue by pixelb** [testing-cabal/linecache2#8]
The description states that this is a backport of linecache to python2

But python 2.6 at least has linecache.

So what is this exactly? More functionality from python3 backported to python2?

**Comment by rbtcollins** [comment]
Functionality from Python 3.6 backported to 2.6,2.7,3.2,3.3,3.4,3.5

**Comment by pixelb** [comment]
Cool thanks. I suggest the README be updated with that.
